// <auto-generated />
using System;
using Fiap.Api.Donation2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240202150503_InicoProdutos")]
    partial class InicoProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation2.Models.CategoriaModel", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Disponivel")
                        .HasMaxLength(5)
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9444),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9461),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 1",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9474),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9475),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 2",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9476),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9476),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 3",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9477),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9478),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 4",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9479),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9479),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 5",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9480),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9480),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9481),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9482),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9482),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9483),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9484),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9484),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9485),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9485),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9487),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9488),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9489),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9489),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9490),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9490),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9491),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9491),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9492),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9493),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9493),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9494),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9494),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9495),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9495),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9496),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9496),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9497),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9497),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9498),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9499),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9499),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9501),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9502),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9503),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9504),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9505),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9505),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9506),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9507),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9508),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9509),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9510),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9510),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9512),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9512),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9513),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9514),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9515),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9516),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 2, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9517),
                            DataExpiracao = new DateTime(2025, 10, 2, 12, 5, 2, 983, DateTimeKind.Local).AddTicks(9517),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation2.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation2.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
