// <auto-generated />
using System;
using Fiap.Api.Donation2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240124004805_AddProdutos")]
    partial class AddProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation2.Models.CategoriaModel", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Disponivel")
                        .HasMaxLength(5)
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4770),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4807),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 1",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4822),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4822),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 2",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4824),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4824),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 3",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4826),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4826),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 4",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4827),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4828),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 5",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4829),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4830),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4831),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4832),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4833),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4833),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4835),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4835),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4876),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4876),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4878),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4878),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4880),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4880),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4881),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4882),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4883),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4883),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4885),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4885),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4886),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4887),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4888),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4888),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4889),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4890),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4891),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4891),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4893),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4893),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4894),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4894),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4896),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4896),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4897),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4898),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4899),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4899),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4900),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4901),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4902),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4902),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4903),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4904),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4905),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4905),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4906),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4907),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4908),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4908),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4909),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 48, 5, 576, DateTimeKind.Local).AddTicks(4910),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation2.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation2.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
